blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/trentnbauer/QueueUp/discussions
    about: Ask a question, propose an idea, or discuss something before filing an issue.
